version: "2.1"

services:
  wine:
    build:
      context: .
    volumes:
      - ${WORKDIR}:${WORKDIR}
    working_dir: ${WORKDIR}
    environment:
      - WORKDIR=${WORKDIR}
    entrypoint: wine

  tinker:
    extends: wine
    entrypoint: bash
